### ISSUE TITLE
Missing "mockup-assets" directory

### ISSUE THREAD

**Issue by ryanrhee** [itsdson/html-mockup#1]
Hey david I think you forgot to include the image files

**Comment by itsdson** [comment]
oh uhh ok let me add them. It was giving me some error code

**Comment by itsdson** [comment]
I think I added it. I've never used github so I might have not added it correctly?

**Comment by ryanrhee** [comment]
you have to add them into a directory called "mockup-assets", not just to the root of the repo haha

**Comment by ryanrhee** [comment]
here i'll put up a pull request that moves them

**Comment by ryanrhee** [comment]
btw can you give me push access? makes this a little faster :p

**Comment by itsdson** [comment]
uhhhh yeah lol let me figure out how to do that.

**Comment by itsdson** [comment]
ok push access done

**Comment by ryanrhee** [comment]
nice. i'll close this issue
